### ISSUE TITLE
imagesフォルダーを上げる方法

### ISSUE THREAD

**Issue by SonedaYusuke** [miyabin66/compression-images#1]
空のフォルダーはgitに反映しないから一般的に.gitkeepっていうファイルを入れてあげるとgitに反映できるようになるよ
https://qiita.com/tommy_aka_jps/items/b2ae85cbeab77e12a925

**Comment by miyabin4113** [comment]
そういうのがあったのか！
ありがとう 🙏

**Comment by miyabin4113** [comment]
対応しました
